# -*- coding: utf-8 -*-
"""Calcite add and diameter steady state code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVbW_ury_rk_x9p6GYEXg8MzwCSXwkIT
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve

d_in = 0.01 #m
M_rock_in = 2.41*10**6 # g
max_iter = 10**6

M_rock = np.zeros(max_iter)
M_rock[0] = M_rock_in

d = np.zeros(max_iter)
d[0]= d_in

molwt =100.0869 #g (CaCO3 mol wt)
rho = 2.71*10**6 #g/m3

b = 0.35 #[-]
a = (1/(2*1e-10))**b #[1/m^b]

lamb=a*d_in**b #[-]
SSA= 6/(d_in*rho)*lamb # [m2/g]
SA = SSA *M_rock_in  #m2

SA_in = SA

sWr = 1.46*10**-6 #mol/m2/s
Wr = np.zeros(max_iter)
Wr[0] = sWr * molwt * SA # mol/m2/s * g/mol * m2
#goal is to maintain the SA

#mass addition to system
mass_add = np.zeros(max_iter)
mass_add[0] = 100 #g/s #initial guess

def mass_addition(m,M,d_reduced,d_in, SA_in):
    SA = 6/rho*a*d_reduced**(b-1) * M + 6/rho*a*d_in**(b-1) * m #factors in that mass added is of d_in diameter

    return  SA - SA_in

d_shrink = sWr*molwt/rho# mol/m2/s * g/mol * m3/g
error = M_rock_in #g (initialising)
t = 0 #initial

while error> 0.05:
    #Shrinking of d and M_rock
    d[t+1] = d[t] - 2*d_shrink*a*d[t]**b
    M_rock[t+1] = M_rock[t] - Wr[t]

    m = mass_add[t]
    d_reduced = d[t+1]
    M = M_rock[t+1]

    #solving mass_add to keep Surface Area constant
    sol = fsolve(mass_addition, m, args = (M,d_reduced,d_in, SA_in), xtol = Wr[0]*10**-3)
    #updating basis solve
    mass_add[t+1] = sol[0]
    M_rock[t+1] = M_rock[t+1] + mass_add[t+1]
    d[t+1] = np.power(SA_in*rho/M_rock[t+1]/6/a, 1/(b-1)) #average diameter basis SA required for that mass (factors in addition of mass of d_in)
    Wr[t+1] = sWr * molwt * SA_in

    error = abs(M_rock[t+1] - M_rock[t])
    t = t+1

print("Initial Rock in = ", np.round(M_rock[0]*10**-6,4), "tons \n rock in the system at equilibrium = ", np.round(M_rock[t]*10**-6,4), "tons")
plt.plot(range(t), M_rock[:t] )
plt.title("Iterative progress of guessing mass of rock in the system at steady state")
print("Iterations required were = ", t)

plt.plot(range(t), d[:t])
plt.title("Iterative progress of guessing average diameter(basis surface area) at steady state")
print("Steady stage average diameter of system =", np.round(d[t]*10**3,4), "mm")

plt.plot(range(t-1), mass_add[1:t]) # initial manual guess can be way off, so display from first iterative guess
plt.title("Iterative progress of guessing mass_add at steady state")
print("Mass add required = ", np.round(mass_add[t],4), "g/s")
print("Mass add per day = ", np.round(mass_add[t]* 86400/10**6, 4) , "tons/day")

